# ONLY FOR LOCALLY BUILDING NOTE-ZEPHYR
manifest:
  projects:
    - name: zephyr
      revision: main
      url: https://github.com/zephyrproject-rtos/zephyr
      import:
        name-allowlist:
          - cmsis_6
          - hal_stm32
