manifest:
  projects:

    - name: note-c
      revision: master
      url: https://github.com/blues/note-c
      path: modules/lib/note-zephyr/note-c

    - name: zephyr
      revision: main
      url: https://github.com/zephyrproject-rtos/zephyr
      import: true

  self:
    path: modules/lib/note-zephyr
