manifest:
  projects:
    - name: zephyr
      revision: main
      url: https://github.com/zephyrproject-rtos/zephyr
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
    - name: mcuboot
      url: https://github.com/zephyrproject-rtos/mcuboot
      revision: main
      path: bootloader/mcuboot
